# author: jinalp60
AWSTemplateFormatVersion: '2010-09-09'
Description: A sample lambda function deployment using cft
Parameters:
  s3Bucket:
    Type: String
    Description: The name of the bucket that contains lambda zip files
  s3Prefix:
    Type: String
    Description: The name of the lambda function zip file uploaded to s3
Resources: 
  CFTLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies: 
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
  SampleLambdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      Handler: index.handler
      Role: !GetAtt CFTLambdaExecutionRole.Arn 
      Runtime: nodejs12.x
      Timeout: 5
      Code:
        S3Bucket: !Ref s3Bucket
        S3Key:  !Ref s3Prefix
    